#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
# xmodmap "/home/livibetter/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox &
fbpid=$!

sleep 1
{
	#setxkbmap -model pc104 -layout us -option compose:rctrl
	#setxkbmap -model pc104 -layout us -option compose:ralt
	urxvtd -q -o -f
	#ibus &
	#nm-applet &
	#gkrellm -w &
    #mpd
#	conky -q &
#	urxvtc -e screen &
	#start-pulseaudio-x11
#	[[ $(lsusb -v | grep -i mouse) ]] && toggle-touchpad.sh 
#	xcompmgr -n &
#	ibus-daemon -d -x
	setxkbmap -model pc104 -layout us -option compose:menu
} &
sleep 5
{
#	gcin &
	dzen-status &
} &

wait $fbpid
