#!/bin/bash
# For Bash interactive shell
# Written by Yu-Jie Lin
# https://github.com/livibetter/dotfiles/tree/master/bash/bash_interactive

source $HOME/.bash/bash_helper_func.sh
source $HOME/.bash/hhrc

#######
# Alias
#######

####
# ls
alias ll='ls -l --color=auto'
alias l.='ls -d .* --color=auto'
alias ls='ls --color=auto'

#####
# vim
__vim() {
  if ((!UID)); then
	/usr/bin/vim "$@"
	return
  fi
  if (( $# > 0 )); then
    /usr/bin/vim --servername VIM --remote-silent "$@"
  else
    /usr/bin/vim --servername VIM
  fi
  }
# ref: http://superuser.com/a/410197/23540
if [[ $(tmux display-message -p '#S' 2>/dev/null) != st-writing ]]; then
  alias vi='__vim'
fi

#######
# misc.
alias cm="./configure --prefix=\$HOME/.local && make"
alias ff='x firefox-bin --new-instance -p Normal --class "Firefox Normal"'
alias lo='x loffice -env:UserInstallation=file://\$HOME/var/libreoffice/Normal'
alias mt='mt.sh | tail'
alias pyhttp='python -m SimpleHTTPServer 8001'
alias tt='cd /tmp;'
alias wdps1="PS1='\\[\\e[1;32m\\]\$(basename -- \"\$PWD\")\\[\\e[0m\\] \\[\\e[1;34m\\]$\\[\\e[0m\\] '"
# For virtual console to launch X window with ease
[[ $TERM == linux ]] && alias x='reset ; exec startdwm'
alias ytdl='cd /tmp ; youtube-dl'

########
# Prompt
########

if enable -f "$(which vimps1)" vimps1 2>/dev/null; then
  PS1='$(vimps1 $?)'
else
  DIR_COLOR='\[\e[1;32m\]'
  USER_COLOR="\[\e[1;$((31 + (UID > 0) * 3))m\]"

  PS1_ERROR='$(ret=$?; ((ret == 0)) ||
printf "\e[41;1;37m%${COLUMNS}s\e[$(((COLUMNS-${#ret})/2))G%s\e[0m\n\[\e[0m\]" "" "$ret"
)'

  PS1="$PS1_ERROR $DIR_COLOR\\w $USER_COLOR\$ \[\e[0m\]"
  unset DIR_COLOR USER_COLOR PS1_ERROR
fi # end of Prompt

# Change the window title of X terminals
# originally from /etc/bash/bashrc on Gentoo
PROMPT_COMMAND='echo -ne "\033]0;${PWD/$HOME/~}\007"'"; ${PROMPT_COMMAND}"

# Goes to /tmp
tt

# vim:ft=sh
